### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by KKongTen** [gus33000/DeviceStream#1]
Hello

I checked your DeviceStream cs file.

I want to access the MBR of the hard disk using the DeviceStream source code you made and access it through the 4BYTE sector of the Cluster of Start VBR through the Partition Table value. 

But I don't know how to use this source code in Maine.

Can you tell me?

**Comment by gus33000** [comment]
Hello and first sorry for the late reply I hope it's not too late or you figured it out. if not

You use it just like a normal Stream class in C#, an example:

```
using (var ds = new DeviceStream("\\.\PhysicalDrive1", FileAccess.Read))
{
 // ds here is just like a normal stream, you can seak read or use a binary reader
}
```

hope this helps!

**Comment by KKongTen** [comment]
> Hello and first sorry for the late reply I hope it's not too late or you figured it out. if not
> 
> You use it just like a normal Stream class in C#, an example:
> 
> ```
> using (var ds = new DeviceStream("\\.\PhysicalDrive1", FileAccess.Read))
> {
>  // ds here is just like a normal stream, you can seak read or use a binary reader
> }
> ```
> 
> hope this helps!

-----------------------------------------------------------------------------------------------
Thank you for response my question. 
I have a question. 
The Constructor of DeviceStream in your devicestream.cs file is designed to bring only String Device. 
The way you told me, var ds = new DeviceStream (String device, FileAccess.Read).

I'm sorry to bother you, but could you give me an example code for extracting MBR 512 bytes throught PhysicalDrive?
